pipeline {
    agent any

    
    stages {
        stage('Build') {
            steps {
                gradle'clean build'
            }}
        
        stage('Unit Tests') {
            steps {
                gradle 'test'
            }}
            }
            post {
                always {
                    junit '**/build/test-results/test/TEST-*.xml'
                }}
        
       
        
}
